### ISSUE TITLE
No se visualiza mi asignacion en formato Md. 

### ISSUE THREAD

**Issue by naui2003** [maestria-geotel-201902/unidad-1-asignacion-1-datos-espaciales-en-r-naui2003#1]
Buenas noches profesor, terminé mi asignación, hice el commit, luego el push y no me sale el archivo en Md, solo el Rmd. Que debo hacer?

**Comment by geofis** [comment]
¿Se relaciona este *issue* con el error de la línea 124 que enviaste en otro *issue*?
