### ISSUE TITLE
Ese es el error que me está arrojando

### ISSUE THREAD

**Issue by naui2003** [maestria-geotel-201902/unidad-1-asignacion-1-datos-espaciales-en-r-naui2003#3]
![image](https://user-images.githubusercontent.com/39661108/67651899-067f1080-f919-11e9-880f-a08534d5e432.png)

Ese es el error que me está arrojando

**Comment by geofis** [comment]
No sé si este *issue* se relaciona con los anteriores, o si además de éste hay más. En cualquier caso, el mensaje lo que está avisando es que no encuentra un objeto. Al parecer, pasaste esto `Simple feature collection with 32 features and 5 fields` como línea a ejecutar; cuando intentaste tejer el `.Rmd` esa línea se pasó a ejecución, pero no puede devolver nada, porque no es código R, y por eso salta el error. La línea 124, no debería estar ahí.
